### ISSUE TITLE
[FEATURE] - Configurer 4 variables pour qu'elles soient paramétrables

### ISSUE THREAD

**Issue by CAMaji** [CAMaji/oxygen-cs-grp2-eq10#20]
## Description de la fonctionnalité
Selon le descriptif du laboratoire 2 : 

"Dans l’application de base, il y a 4 variables qui pourraient être paramétrées pour faciliter la configuration selon les besoins et l’environnement.

Si la variable d’environnement n’est pas définie, vous devez avoir une valeur par défaut. Si le token n’est pas défini en variable d'environnement, l'application doit retourner une erreur."

## Niveau de priorité (critique, important, ou utile)
Niveau important

**Comment by CAMaji** [comment]
#19 doit être fait en premier pour le débloquer.

**Comment by Tzuyunii** [comment]
Cette tache est réalisée sur la branche #19
