### ISSUE TITLE
[FEATURE] - Kubernetes - Créer les ConfigMap

### ISSUE THREAD

**Issue by CAMaji** [CAMaji/oxygen-cs-grp2-eq10#68]
## Description de la fonctionnalité
Il faut créer des ConfigMap pour les variables d'environnements qui ne sont pas des secrets.

## Niveau de priorité (critique, important, ou utile)
Niveau important

**Comment by Tzuyunii** [comment]
Cette tache est effectuée dans la même branche que le #70
