### ISSUE TITLE
[FEATURE] - Kubernetes - Créer les Secrets

### ISSUE THREAD

**Issue by CAMaji** [CAMaji/oxygen-cs-grp2-eq10#69]
## Description de la fonctionnalité
Il faut ajouter des secrets pour le HVAC_TOKEN et peut-être le TOKEN aussi.

## Niveau de priorité (critique, important, ou utile)
Niveau important

**Comment by Tzuyunii** [comment]
Cette tache est effectuée dans la même branche que le #70
