### ISSUE TITLE
[FEATURE] - Kubernetes - Créer les deployments

### ISSUE THREAD

**Issue by CAMaji** [CAMaji/oxygen-cs-grp2-eq10#70]
## Description de la fonctionnalité
Il faut ajouter les deployments pour faciliter la maintenance des conteneurs Docker.

## Niveau de priorité (critique, important, ou utile)
Niveau important

**Comment by Tzuyunii** [comment]
Il parait que c'est fonctionnel maintenant!

![Image](https://github.com/CAMaji/oxygen-cs-grp2-eq10/assets/28740959/23db1ee9-17cd-4f17-ab5f-5421e4829b8e)
